[graph]
targets = [
    "x86_64-unknown-linux",
    "x86_64-unknown-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
all-features = true

[bans]
multiple-versions = "deny"

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"]
